apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: golubev-lundev-net-tls
spec:
  secretName: golubev-lundev-net-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: golubev.lundev.net
  dnsNames:
    - golubev.lundev.net
    - www.golubev.lundev.net
